- node/packages/functional-tests/src/server.ts
- node/packages/sdk/src/adapters/adapter.ts
- node/packages/sdk/src/adapters/multipeer/adapter.ts
- node/packages/sdk/src/adapters/websocket/adapter.ts
- node/packages/sdk/src/log.ts
- node/packages/sdk/src/webHost.ts
- Better interface for logging messages to the application.
- Log baseUrl and baseDir at startup.
- Ported functional tests to use WebHost.
> Improved logging to app

- .vscode/launch.json
- packages/sdk/src/adapters/multipeer/adapter.ts
- packages/sdk/src/adapters/websocket/adapter.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/webHost.ts
- Propagate promise rejections back to application code when appropriate (we were sinking them).
- Fixed some internal bugs in the new logging subsystem.
- Improved error messaging.
> Multiple fixes to error handling

- README.md
The gl in glTF is always lower case as per the official homepage https://www.khronos.org/gltf/
> GLTF -> glTF

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/primitives-test.ts
- packages/functional-tests/src/tests/root-motion-test.ts
added root motion test, improved input and clock test
shortened time on primitives test
fixed bad name string on asset preload test
> functional test improvements

- packages/functional-tests/package-lock.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/sdk/package-lock.json
- packages/sdk/src/types/internal/context.ts
Also created a glTF loading stress test.
> Reject CreateFrom* promises if Unity reports load failure

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/user-test.ts
Shows information about the launching user, and the total number of users in the session.
PR is towards "awaiting", as it depends on the User changes to the functional test framework, which are coming in as part of the LookAt changes.
> Added User functional test 

- packages/sdk/src/types/runtime/actor.ts
> Wait for actor creation to complete before triggering a state update.

- .vscode/tasks.json
- packages/altspacevr-extras/.npmignore
- packages/altspacevr-extras/LICENSE
- packages/altspacevr-extras/README.md
- packages/altspacevr-extras/package-lock.json
- packages/altspacevr-extras/package.json
- packages/altspacevr-extras/src/index.ts
- packages/altspacevr-extras/src/videoPlayerManager.ts
- packages/altspacevr-extras/tsconfig.json
- packages/functional-tests/package.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/altspacevr-extras-test.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/tsconfig.json
- packages/tsconfig.lint.json
- tsconfig.json
(requires AltspaceVR runtime changes to support the new RPC call)
> Set up AltspaceVR extras NPM Package, and added video player

- .gitignore
- packages/altspacevr-extras/src/videoPlayerManager.ts
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/test.ts
- packages/sdk/src/rpc/rpc.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/runtime/assets/assetManager.ts
- packages/sdk/src/types/runtime/context.ts
- packages/sdk/src/utils/bufferedEventEmitter.ts
and clean up event handlers on context exit, clean up actors and event handlers on test complete
> display on-screen error if functional test fails/throws exception. 

- packages/functional-tests/src/tests/altspacevr-video-test.ts
let's not place the movie screen 2/3 into the ground, please
> movie player functional test tweaks

- DEVELOPER_WORKFLOW.md
- README.md
just some tweaks after the first deployment.
> minor revisions

- packages/sdk/src/adapters/multipeer/adapter.ts
- packages/sdk/src/adapters/websocket/adapter.ts
- packages/sdk/src/types/internal/context.ts
Removal of BufferedEventEmitter combined with my multipeer refactor created an order of operations issue during session startup.
> Start the app context _after_ the app is instantiated.

- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/network/subscriptionType.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/user.ts
Removed the notion of user subscriptions and user transform. We weren't using them, and probably never will.
> [SDK] Remove unused code

- packages/sdk/src/types/runtime/assets/assetManager.ts
> Fix: assets not registered during explicit creation

- packages/sdk/src/index.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/attachment.ts
- packages/sdk/src/types/runtime/index.ts
Adds the `attachment` actor component. Attachment state changes are sent in the actor update patch and applied client side.
- Attachments functional test. Will come as a separate PR.
> [SDK] Avatar attachments

- packages/functional-tests/src/tests/user-test.ts
- packages/sdk/src/protocols/execution.ts
- packages/sdk/src/types/runtime/user.ts
Just a small one to guarantee the presence of what I think should be dependable user properties.
> Guarantee presence of user properties "host" and "engine"

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
During this process, I realized I forgot to finish porting the library test, so that work is done here as well.
> Update test for new altspace library format

- .gitignore
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/asset-early-assignment-test.ts
- packages/functional-tests/src/tests/asset-mutability-test.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/gltf-animation-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/interpolation-test.ts
- packages/functional-tests/src/tests/light-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/src/tests/primitives-test.ts
- packages/functional-tests/src/tests/reparent-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/functional-tests/src/tests/text-test.ts
- packages/functional-tests/src/tests/user-test.ts
- packages/sdk/src/math/color3.ts
- packages/sdk/src/sound/setSoundStateOptions.ts
changed FT orientation to be visible without rotating space component
Made all items above ground (y>0) and in front of wall (z<0).
added ground and wall geometry
moved everything to be within (or nearly within) the floor area.
added lights to some scenes that were hard to see
moved menu to the wall, and stop/return buttons to the front
> functional test polish

- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/sdk/src/sound/setSoundStateOptions.ts
renamed a field or two
undid a couple of temporary functional test hacks, now we have better audio sync and actor sync
> [sdk] Soren/sound api polish

- .gitignore
- packages/functional-tests/package-lock.json
- packages/functional-tests/package.json
- packages/functional-tests/src/server.ts
The dotenv package reads environment variables from a .env file and populates `process.env` with them. This allows us to put configuration in a file. I need this for running multiple MREs on a single Azure VM.
> Add dotenv package

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/asset-early-assignment-test.ts
- packages/functional-tests/src/tests/asset-mutability-test.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/gltf-animation-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/functional-tests/src/tests/grab-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/interpolation-test.ts
- packages/functional-tests/src/tests/light-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/src/tests/physics-sim-test.ts
- packages/functional-tests/src/tests/primitives-test.ts
- packages/functional-tests/src/tests/reparent-test.ts
- packages/functional-tests/src/tests/rigid-body-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/functional-tests/src/tests/text-test.ts
- packages/functional-tests/src/tests/transform-test.ts
- packages/functional-tests/src/tests/user-mask-test.ts
- packages/functional-tests/src/tests/user-test.ts
- packages/functional-tests/src/tests/visibility-test.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/actorTransform.ts
- packages/sdk/src/types/runtime/index.ts
- packages/sdk/src/types/runtime/transform.ts
API update now has an actor transform that contains a local space scaled transform and an app space non-scaled transform.
Accessing the transform's by space is performed as:
- Local: `actor.transform.local`
- App: `actor.transform.app`
```
actorPatch = {
…,
transform: {
app: {
position: Vector3,
rotation: Quaternion
},
local: {
position: Vector3,
rotation: Quaternion,
scale: Vector3
}
}
```
> Transform API Update for App and Local Spaces

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
- packages/functional-tests/src/tests/user-mask-test.ts
- packages/sdk/src/protocols/execution.ts
- packages/sdk/src/types/internal/actor.ts
- packages/sdk/src/types/runtime/behaviors/action.ts
- packages/sdk/src/types/runtime/behaviors/actionEvent.ts
- packages/sdk/src/types/runtime/behaviors/behavior.ts
- packages/sdk/src/types/runtime/behaviors/buttonBehavior.ts
- packages/sdk/src/types/runtime/behaviors/targetBehavior.ts
This PR changes all interfaces into the Behavior system from user IDs into resolved User objects.
> Behavior callbacks pass User objects, not IDs

- package-lock.json
- package.json
- packages/altspacevr-extras/package-lock.json
- packages/functional-tests/package-lock.json
- packages/gltf-gen/package-lock.json
- packages/sdk/package-lock.json
Run `npm audit fix` on all the packages.
> Fix dependency vulnerabilities

- packages/functional-tests/src/tests/asset-mutability-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
So we notice if transparency works
> Add transparency to material tests

- packages/sdk/src/types/runtime/rigidbody.ts
Referenced by issue #[344](https://github.com/microsoft/mixed-reality-extension-sdk/issues/344)
> Add in IsKinematic property to rigid body

- packages/sdk/src/types/runtime/rigidbody.ts
Crept in when I added in the documentation headers in the IsKinematic PR merge.
> Fixed a whitespace issue for TSLint to be happy again.

- DEPLOYING.md
Updated Deploying.md with my steps to deploy to Azure App Service using Visual Studio Code.
> Added VSCode Azure deployment steps

- packages/sdk/src/adapters/multipeer/rules.ts
> Check array length before accessing it

- package-lock.json
- package.json
Updating lerna in order to resolve npm security warnings.
> Update to lerna 3.16.1

- packages/sdk/src/types/internal/context.ts
> Stop loading on actor destroy

- packages/sdk/src/types/runtime/assets/material.ts
> Apply textures in mat patches when provided

- packages/sdk/src/adapters/multipeer/session.ts
> Correctly merge local/app transforms

- README.md
> Readme.md - Replaced slack with discord

- .vscode/launch.json
- .vscode/tasks.json
- packages/functional-tests/src/tests/actor-spam-test.ts
- packages/functional-tests/src/tests/index.ts
* Add actor spam functional test.
* Change VS Code config to automatically recompile the functional tests before launching them.
> Add actor spam functional test

- .vscode/tasks.json
- Dockerfile
- packages/altspacevr-extras/.npmignore
- packages/altspacevr-extras/LICENSE
- packages/altspacevr-extras/README.md
- packages/altspacevr-extras/package-lock.json
- packages/altspacevr-extras/package.json
- packages/altspacevr-extras/src/index.ts
- packages/altspacevr-extras/src/videoPlayerManager.ts
- packages/altspacevr-extras/tsconfig.json
- packages/functional-tests/package.json
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/index.ts
- packages/functional-tests/tsconfig.json
- packages/tsconfig.lint.json
- tsconfig.json
Also updated it to the latest RPC interface.
> Reinstate altspacevr-extras

- .vscode/launch.json
- design/collider.layer.md
- packages/functional-tests/src/tests/collision-layer-test.ts
- packages/functional-tests/src/tests/index.ts
- packages/functional-tests/src/tests/physics-sim-test.ts
- packages/functional-tests/src/utils/animations.ts
- packages/functional-tests/src/utils/tableLayout.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/assets.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/collider.ts
* Add design doc for collision layers.
* Implement the (minimal) changes needed for layers in the SDK.
* Add collision layer functional test.
> [SDK] Collision layers

- packages/functional-tests/src/tests/collision-layer-test.ts
The platform is useful for determining if player collision is happening.
> Add platform to collision layer test

- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/gltf-gen/src/geometry/index.ts
- packages/gltf-gen/src/geometry/plane.ts
- packages/gltf-gen/src/geometry/quad.ts
- packages/gltf-gen/src/meshprimitive.ts
- packages/gltf-gen/src/vertex.ts
- packages/gltf-gen/src/vertexattributes.ts
- packages/sdk/src/actor/behaviors/buttonBehavior.ts
- packages/sdk/src/actor/behaviors/targetBehavior.ts
- packages/sdk/src/asset/material.ts
- packages/sdk/src/asset/mesh.ts
- packages/sdk/src/asset/prefab.ts
- packages/sdk/src/asset/sound.ts
- packages/sdk/src/asset/texture.ts
- packages/sdk/src/asset/videoStream.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientExecution.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientHandshake.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientStartup.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionExecution.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionHandshake.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionSync.ts
- packages/sdk/src/internal/connection/eventedConnection.ts
- packages/sdk/src/internal/connection/webSocket.ts
- packages/sdk/src/internal/protocols/execution.ts
- packages/sdk/src/internal/protocols/handshake.ts
- packages/sdk/src/internal/protocols/sync.ts
- packages/sdk/src/internal/util/verifyClient.ts
- packages/sdk/src/util/webHost.ts
* Change gltf-gen color vertex attribute type from Vector3 to Color4
* Add Quad and Plane primitives
> [gltf-gen] Convert color vertex attribute to Color4, more prims

- packages/sdk/src/user/user.ts
There's a case sensitivity issue.
> Fix compilation on Linux (Docker)

- packages/sdk/src/internal/adapters/multipeer/rules.ts
> Fix lint errors

- packages/sdk/src/actor/text.ts
* Add a monospace font for use by MRE text objects
* Add a cursive/handwriting font
> [SDK] Add more font types

- packages/sdk/src/internal/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/internal/adapters/multipeer/session.ts
- packages/sdk/src/internal/adapters/multipeer/syncAnimation.ts
> Fix animation sync for late-joining clients

- packages/sdk/src/actor/actor.ts
> Add more detail to docs for Actor.CreateFromLibrary

- design/assets.unity.md
Create a new design for caching web-based assets in a safe and reusable manner.
> Asset cache design review

- DEVELOPER_WORKFLOW.md
Some stuff was getting out of date. I've updated the release docs to more accurately reflect what I've been doing in practice, to streamline the tasks.
> Update release workflow

- packages/sdk/src/actor/physics/physicsBridge.ts
Sleeping bodies message update
> Sleeping bodies message update

- design/user-id-update.md
This is a design that will meet my concerns about current user ID design
> user id proposed change in design

- design/behavior.system.md
This is being added to begin documenting the behavior system design in to the SDK design documentation.  The main focus is in the design of how we react to the user interaction permission, so that section is fairly detailed and should be the focus of the PR, though feedback elsewhere is welcome.  I will be filling out the other sections at a later time in a different PR, however.
See [PR#207](https://github.com/microsoft/mixed-reality-extension-unity/pull/207) for implementation
> Add in WIP behavior system design with detailed permission section

- DEPLOYING.md
> Updated instructions about Azure deployment (#474)

- packages/functional-tests/src/tests/font-test.ts
- packages/functional-tests/src/tests/index.ts
Test is as simple as start and observe. All our fonts are stress-tested with Latin, Korean, Japanese, and Chinese characters, which cycle automatically every 3 seconds.
> Adding FontTest to test Altspace's fonts with a variety of Unicode ranges

- packages/sdk/src/util/webHost.ts
For MREs that want to add additional routes to the HTTP server, you need to wait for the server to be created before you can add your routes. This new promise tells you that the server is created and ready to go.
> Add a ready promise to WebHost

- packages/functional-tests/src/tests/asset-mutability-test.ts
Test for a new bug where usages of a material are not correctly identified and substituted for a write-safe version.
> Test write-safe materials in asset mutability test

- packages/sdk/src/asset/sound.ts
Adding ability to specify type of audio stream when the underlying systems can't deduce it from the URI alone.
> Sound type
