- .vscode/launch.json
- .vscode/tasks.json
- packages/sdk/src/webHost.ts
At startup, log Node and SDK versions to the console.
Startup log looks something like this now:
```
app Node: v8.12.0 +0ms
app @microsoft/mixed-reality-extension-sdk: v0.2.1 +2ms
app Multi-peer Adapter listening on {"address":"::","family":"IPv6","port":3901} +11ms
app baseUrl: http://127.0.0.1:3901 +1ms
app baseDir: D:\mixed-reality-extension-sdk\packages\functional-tests\public +0ms
```
Other changes:
- Don't try to infer `baseDir`. There's no reliable way to do this.
- Only serve static files if `baseDir` was provided.
> Log node and sdk versions at startup

- .vscode/launch.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/asset-preload.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/gltf-gen/package-lock.json
- packages/gltf-gen/package.json
- packages/sdk/package-lock.json
- packages/sdk/package.json
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/lookatMode.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/runtime/actor.ts
This is the TypeScript side of the LookAt changes discussed on Teams. One change in here not discussed: The "preserve original rotation" feature was being problematic when the app itself was rotated, so I removed it for now.
LookAt is now invoked by calling a method on Actor, similar in spirit to `startAnimation`, etc. It can look at another Actor or User known to the app:
```ts
public lookAt(targetOrId: Actor | User | string, lookAtMode: LookAtMode);
```
> LookAt updates

- packages/functional-tests/src/app.ts
if instantiating functional tests without a parameter then create a menu.
At this point the menu doesn't repopulate after completion, but that appears to be due to a bug somewhere else.
> Functional Test Browser

- package.json
- packages/functional-tests/package-lock.json
- packages/functional-tests/package.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/src/tests/text-test.ts
- packages/gltf-gen/package.json
- packages/sdk-azure/package.json
- packages/sdk/package.json
- packages/tsconfig.lint.json
lint was disabled on functional test framework - this enables it, and makes sure we build each package before linting it, so we don't worry about lint errors on non-compiling code.
> enable lint on functional tests

- DEPLOYING.md
- packages/functional-tests/package.json
This is what I needed to changed for the openode.io deploy to just work for functional tests.
I couldn't explain why tslib is needed and our local builds don't complain about it, so I'm adding in the reference for now and an issue to track it whenever we need to debug it
> changes needed to deploy functional tests to openode

- packages/sdk/package.json
- packages/sdk/src/adapters/multipeer/adapter.ts
Currently, the remote address passed to the client's user.properties.remoteAddress is just the address of the last hop connecting to the MRE.
This fails whenever a proxy forwarded this request, e.g. Heroku's load balancers - the IP address shown would be the outgoing interface of the load balancer.
This change includes 'forwarded-for' which scans the HTTP headers for 'well-known' forwarder header lines like 'x-forwarded-for' and adjusts the IP address to be passed on accordingly. Without a proxy inbetween, forwarded-for would take the original remoteAddress of the request.
> Respect proxy/forwarder headers when determining the connection's source

- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/runtime/actor.ts
Also make `options` parameter to CreateEmpty optional, since all its members are optional.
> [SDK] Protection against undefined options

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/mutable-asset-test.ts
- packages/sdk/src/types/internal/actor.ts
- packages/sdk/src/types/internal/asset.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/internal/material.ts
- packages/sdk/src/types/network/payloads/assets.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/patchable.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/assets/asset.ts
- packages/sdk/src/types/runtime/assets/assetManager.ts
- packages/sdk/src/types/runtime/assets/material.ts
- packages/sdk/src/types/runtime/assets/prefab.ts
- packages/sdk/src/types/runtime/context.ts
* Updated `Material` to generate patches.
* Implemented interfaces `Patchable<T>` and `InternalPatchable<T>`, which the context uses to check for updates.
* `StateUpdate` messages can now contain both `ActorUpdate`s and `AssetUpdate`s.
* Added a new functional test that demonstrates shared mutable materials.
* Renamed the context asset manager to `assetManager` from `assets`. Also rearranged some APIs in the manager for better usability.
> [SDK] Asset mutability

- packages/functional-tests/src/tests/gltf-animation-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/tslint.json
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/runtime/actor.ts
Renamed for naming consistency with AssetManager.loadGltf and elsewhere. For backward compatibility the old call is deprecated rather than deleted.
> Rename CreateFromGLTF -> CreateFromGltf

- packages/sdk/src/utils/filterEmpty.ts
This function threw an exception if `null` were passed in, as its type is `'object'`, but doesn't support Object.keys.
> Fix serialization failure when nulling synced actor property

- packages/functional-tests/tsconfig.json
- packages/sdk/src/types/runtime/actor.ts
tslint doesn't report this when I build from vscode, but does when building from command line. Thanks goes to @renebohne for the heads up.
Also: Fixed up a missing project dependency.
> Add missing catch statement

- packages/sdk/src/types/runtime/transform.ts
This was incorrect, and causing headaches when trying to pass transform.position into a math functions like vec.subtract, since math function don't (and shouldn't) take partials.
> Remove Partial<> from Transform members

- packages/sdk/src/adapters/multipeer/client.ts
- packages/sdk/src/adapters/multipeer/index.ts
- packages/sdk/src/adapters/multipeer/protocols/clientExecution.ts
- packages/sdk/src/adapters/multipeer/protocols/clientHandshake.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/protocols/sessionExecution.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/adapters/multipeer/syncActor.ts
- packages/sdk/src/connection/connection.ts
- packages/sdk/src/connection/nullConnection.ts
- packages/sdk/src/connection/pipe.ts
- packages/sdk/src/connection/webSocket.ts
- packages/sdk/src/protocols/execution.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/payloads.ts
A clear pattern finally emerged in the way the multi-peer adapter handle's different kinds of network messages at various stages of handshake, join-in-progress, and regular operation.
This refactor formalizes that pattern, standardizing how message handling is configured for every payload type at different join stages. Comprehensive message handling "rules" are defined in a new file called 'rules.ts'.
The code is still complex, but hopefully more understandable and maintainable now.
Fixes: #110, #141, #130, the bug where the actor transform was always synced, and probably others.
This is a big PR. Review what you can.
> Big cleanup of message handling in the multi-peer adapter

- packages/sdk/package-lock.json
- packages/sdk/package.json
- packages/sdk/src/adapters/multipeer/adapter.ts
- packages/sdk/src/adapters/websocket/adapter.ts
- packages/sdk/src/constants.ts
- packages/sdk/src/utils/verifyClient.ts
Soren and I worked out a new version checking scheme: Client reports current client version and minimum supported SDK version. App checks this against minimum supported client version and current SDK version. If current client version >= minimum supported client version && current SDK version >= minimum supported SDK version, the connection is allowed.
> [SDK] New version compatibility scheme

- packages/functional-tests/src/tests/interpolation-test.ts
Now just shows an expressive cube, interpolating rotation and scale. Click on it to exit or wait one minute.
> Simplify interpolation test

- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/mutable-asset-test.ts
- packages/gltf-gen/src/geometry/sphere.ts
- packages/sdk/src/constants.ts
- packages/sdk/src/math/vector2.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/assets/material.ts
- packages/sdk/src/types/runtime/assets/texture.ts
- packages/sdk/src/utils/deterministicGuids.ts
* Instrument Vector2 to be patchable
* Add a ZeroGuid constant
* FIll out the Texture asset class
* Add a texture, offset, and scale to Materials
* Update functional tests to use new features
> [SDK] Texture asset support

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/server.ts
- packages/functional-tests/src/tests/reparent-test.ts
Also sorting of the test list got lost in a merge somewhere so I restored it.
> Add reparenting functional test

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/tests/asset-early-assignment.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/types/network/payloads/assets.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/runtime/assets/asset.ts
- packages/sdk/src/types/runtime/assets/assetManager.ts
- packages/sdk/src/types/runtime/assets/material.ts
- packages/sdk/src/types/runtime/assets/mesh.ts
- packages/sdk/src/types/runtime/assets/prefab.ts
- packages/sdk/src/types/runtime/assets/texture.ts
* Make the asset constuctors take partials, and safely handle missing values.
* Add a `uri` field to `TextureLike`s for tracking texture sources separately from asset group sources.
* Refactor `AssetManager.ready` to be a promise chain instead of a dynamically created Promise.all call. New loads simply append their load to the chain. This dramatically reduces the complexity of the system.
* Added a default "manual" asset group that contains all individually created assets.
* Add `AssetManager.createMaterial(name: string, definition: MaterialLike): ForwardPromise<Material>`
* Add `AssetManager.createTexture(name: string, definition: TextureLike): ForwardPromise<Texture>`
> AssetManager.createMaterial, createTexture, ready

- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/network/payloads/payloads.ts
Fixed an out of date network payload. Non-critical, but was causing the latency calculation to be ignored during animation sync.
> [SDK] Minor fix to animation sync

- packages/sdk/src/types/runtime/assets/assetManager.ts
Fixes functional test errors on successive runs
> Return existing asset group if load source is the same

- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/network/payloads/physics.ts
The enable-* payloads have all been removed in favor of using the existing actor patching mechanism whenever possible in order to minimize complexity in the sync layer. @tombuMS you should be able to sync collider state updates the same as other actor components (rigid body, light, text). Let me know if that isn't going to work and we'll figure something out.
> Remove enable-collider payload

- .vscode/tasks.json
- packages/sdk/src/adapters/multipeer/adapter.ts
- packages/sdk/src/adapters/multipeer/client.ts
- packages/sdk/src/adapters/multipeer/protocols/clientExecution.ts
- packages/sdk/src/adapters/multipeer/protocols/clientHandshake.ts
- packages/sdk/src/adapters/multipeer/protocols/clientStartup.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/connection/webSocket.ts
- packages/sdk/src/protocols/handshake.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/message.ts
Found and fixed numerous issues exposed by stressing network traffic in different ways.
- Fix for #188: "Multi-peer bug: Queued actions can be sent before actor is ready." When the app sends a message that expects a reply, the multipeer adapter will now wait for replies from all peers before forwarding the reply back to the app.
- There was a small window of time between client 'handshake' and 'startup' steps where a message could get dropped. It's a weakness in the protocol design. Added a workaround for now. Will revisit the design later.
- During animation synchronization there's an edge case that could result in an unexpected reply message. Added a workaround for that. This issue will go away soon with the planned anim sync refactor.
- All messages that expect a reply must be able to …
> [SDK] Fixes for stability

- packages/sdk/src/adapters/multipeer/client.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/protocols/protocol.ts
This PR contains three bugfixes:
1. A race condition in the client join process vs. how we were tracking the authoritative peer could cause a mismatch between which peer the server considered authoritative and which client was acting as the authoritative peer. Bug symptoms include: Behaviors not responding on non-authoritative instances. We've seen this a lot in the wild, where something isn't clickable. Really great to have tracked this one down.
2. A regression introduced in my last PR would cause every non-authoritative peer to repeatedly disconnect after a minute then reconnect. Doh!
3. A regression introduced in my last PR where client replies weren't getting preprocessed, resulting in gaps in the cached synchronization state. Doh!
To whoever added the Connect and Disconnect buttons …
> [SDK] More networking fixes

- packages/functional-tests/src/tests/interpolation-test.ts
- packages/functional-tests/src/tests/light-test.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/utils/readPath.ts
**Fixes**
- AnimateTo should not have a reply message. This was causing the app to hang when one user left.
- readPath (in patching system) should not die on undefined values. Now it just ignores them.
- During client sync, we don't have a reliable way to know whether to send reply messages back to the app, so now we just send them all back and let the app's protocol layer sort it out.
**Unresolved issues**
- When a client disconnects, we don't clean up outstanding promises for messages awaiting replies. This will cause a timeout and kill the session.
- When the session is killed this way, it doesn't clean up properly.
- I will follow up on these Monday.
> Multiple fixes for issues uncovered while running functional tests

- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
After playing a sound, new users weren't able to fully sync up to the app. This was the culprit.
> set-sound-state shouldn't expect a response during sync

- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/runtime/actor.ts
if you created the behavior before actor had resolved, this warning would have triggered unnecessarily.
(After doing this, realized it may be affected by your refactor, Eric)
> moved 'behavior needs collider' warning to happen after actor created

- packages/functional-tests/src/tests/asset-mutability-test.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/gltf-animation-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/gltf-gen-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/types/internal/actor.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/message.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/soundInstance.ts
With this change, the SDK no longer waits for actor creation to complete before sending subsequent actor commands. The same for create-animation, etc. All messages are sent to the client where they're handled appropriately depending on the state of the actor. This greatly simplifies the multipeer sync layer, as well as lowering the SDK's need for reply messages overall.
PONDER: Should the asset system do something similar? What about interdependencies between the two systems?
> [SDK] Move message queuing to the client

- packages/sdk/src/types/primitiveTypes.ts
- packages/sdk/src/types/rigidBodyConstraints.ts
- packages/sdk/src/types/runtime/assets/material.ts
- packages/sdk/src/types/runtime/text.ts
This is a cleanup pass on our enum values to use a dash-formatted, lower-case format. For the sake of back-compatibility, I won't merge this PR until https://github.com/Microsoft/mixed-reality-extension-unity/pull/33 has been integrated into AltspaceVR and released.
> [SDK] Standardize on lower-case, dash-formatted enum values.

- package.json
- packages/functional-tests/src/app.ts
- packages/sdk/src/utils/parseNetworkLogs.ts
- packages/sdk/src/utils/safeAccessPath.ts
Its output is pretty rough, but it serves its purpose. For a single app session, plus for each connected client, the script outputs a column of incoming and outgoing messages, sorted chronologically.
```
15:00:40 (ebfe09) create-primitive =>
15:00:40                               => (ebfe09) create-primitive
15:00:40                                                             => (ebfe09) create-primitive
15:00:40                                                    (ebfe09) <= (8d32b8) object-spawned
15:00:40                      (ebfe09) <= (2ce3c6) object-spawned
15:00:40 (2ce3c6) object-spawned <= ebfe09
```
> Add util to parse network logs into an event diagram

- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/protocols/execution.ts
- packages/sdk/src/protocols/protocol.ts
- Fixed a misconfiguration in the set-behaviors sync stage.
- Made it easier to selectively treat unexpected reply messages as non-errors.
- Clarified a comment about the status of the actor-correction payload.
> [SDK] Misc synchronization fixes and improvements

- packages/sdk/src/adapters/multipeer/client.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/log.ts
- packages/sdk/src/protocols/protocol.ts
- packages/sdk/src/webHost.ts
The logging system can now be configured from the `MRE_LOGGING` environment variable.
Simple example:
```bash
MRE_LOGGING=app,network,network-content
```
You can disable logging by area by prefixing with a `-`:
```bash
MRE_LOGGING=-app
```
You can be selective about the severity levels to enable and disable:
```bash
MRE_LOGGING=-app:info,network:error
```
Also: Replaced calls to console.error with calls to logging system.
> Log system improvements

- packages/functional-tests/src/tests/gltf-actor-sync-test.ts
- packages/functional-tests/src/tests/index.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
- packages/sdk/src/adapters/multipeer/syncActor.ts
Prior to this PR, patches to actors created from glTF (other than the root actor) were getting stored but never sent.
> Properly sync actors created from glTF

- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/grab-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/functional-tests/src/tests/user-mask-test.ts
- packages/sdk/src/types/runtime/behaviors/buttonBehavior.ts
This will allow for the differentiation of these button events for long press grabs and clicks on 3dof and 2d within host apps where button conflicts happen for grab and button interactions.
NOTE: The previous click event that was pressed and released is now a higher level click event that only happens when a long press has not happened and been handled by a grab.  A new button event has been added for raising events in the app on a button pressed and released.
> Updated button event API for button vs click events

- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/network/payloads/payloads.ts
- packages/sdk/src/types/runtime/actor.ts
This is a cleanup associated with some redundancy in the subscriptions API as well as moving the subscription updates in to the actor patch.
This is referenced in issue #[318](https://github.com/microsoft/mixed-reality-extension-sdk/issues/318)
> Make subscriptions only a part of the patch.

- packages/functional-tests/src/server.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/types/network/payloads/payloads.ts
This adds in lerping for the synchronized clients during a grab.  This is performed through the existing actor correction payload that is no fully hooked up and supported.
Referenced by issue #[320](https://github.com/microsoft/mixed-reality-extension-sdk/issues/320)
> Grab lerping on synchronized clients

- DEPLOYING.md
Update deployment readme instructions to include the step to update the baseUrl of the WebHost to properly serve assets.
> Update deployment readme instructions

- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/adapters/multipeer/session.ts
* When it comes to glTFs and other implicitly created actors, don't overwrite the pristine load state with the patch's placeholders for the same state. This was assigning default materials and overwriting the client-only materials from the glTF.
* When caching transform updates in the session, only save one of app and local coordinates. Saving both requires recomputing after asymmetric updates, which is unnecessarily complicated.
> Maintain app/local transform sync in multipeer session

- packages/functional-tests/src/tests/index.ts
- packages/functional-tests/src/tests/library-fail-test.ts
Something about Unity-side exceptions kills the whole MRE update loop, even if they're caught.
> Add test that "freezes" MREs

- packages/sdk/src/adapters/multipeer/client.ts
- packages/sdk/src/adapters/multipeer/protocols/clientExecution.ts
- packages/sdk/src/adapters/multipeer/protocols/clientHandshake.ts
- packages/sdk/src/adapters/multipeer/protocols/clientStartup.ts
- packages/sdk/src/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/adapters/multipeer/rules.ts
- packages/sdk/src/protocols/protocol.ts
Timeouts are now set for these message types only:
- handshake
- heartbeat
- sync-animations (and this one will be going away soon)
Your MRE can now stack up 100s of load-gltf calls and it won't disconnect all your mobile users :)
Fixes #315
> Support for selective message timeouts

- .vscode/tasks.json
- package-lock.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/altspacevr-library-test.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/clock-sync-test.ts
- packages/functional-tests/src/tests/gltf-actor-sync-test.ts
- packages/functional-tests/src/tests/gltf-animation-test.ts
- packages/functional-tests/src/tests/gltf-concurrency-test.ts
- packages/functional-tests/src/tests/grab-test.ts
- packages/functional-tests/src/tests/input-test.ts
- packages/functional-tests/src/tests/interpolation-test.ts
- packages/functional-tests/src/tests/library-fail-test.ts
- packages/functional-tests/src/tests/light-test.ts
- packages/functional-tests/src/tests/look-at-test.ts
- packages/functional-tests/src/tests/physics-sim-test.ts
- packages/functional-tests/src/tests/primitives-test.ts
- packages/functional-tests/src/tests/reparent-test.ts
- packages/functional-tests/src/tests/rigid-body-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/functional-tests/src/tests/text-test.ts
- packages/functional-tests/src/tests/transform-test.ts
- packages/functional-tests/src/tests/user-mask-test.ts
- packages/functional-tests/src/tests/user-test.ts
- packages/functional-tests/src/tests/visibility-test.ts
- packages/sdk/src/types/internal/actor.ts
- packages/sdk/src/types/internal/context.ts
- packages/sdk/src/types/runtime/actor.ts
> [SDK] Remove ForwardPromise from actor creation calls

- packages/functional-tests/src/server.ts
- packages/sdk/src/log.ts
- packages/sdk/src/protocols/execution.ts
Instead of client library traces going into the "network" category, they have their own category, and are enabled by default in functional tests. This is part of #24 , and builds on the logging PR on the unity repo.
> moved client traces into a separate logging facility

- packages/sdk/package-lock.json
- packages/sdk/package.json
v0.12.2 included updating to a fork of an upstream dependency. That fork has been merged back into upstream, so this PR retargets package.json to the upstream NPM repo instead of GitHub.
> Retarget forwarded-for dependency to NPM

- packages/sdk/src/types/runtime/assets/assetContainer.ts
> Apply read-only asset properties after load

- packages/functional-tests/src/tests/physics-sim-test.ts
Fix #436 
The label was sunk into the back plate somehow. Confusing, given that my PR didn't change that transform value.
> Move ball counter label

- packages/sdk/src/adapters/multipeer/session.ts
If a sound/video is played before it finishes loading, the sync layer can have an `undefined` expiration time, which prevents the instance from getting cleaned up after play is complete.
> Late media expiration time update

- .vscode/tasks.json
- packages/functional-tests/src/app.ts
- packages/functional-tests/src/menu.ts
- packages/functional-tests/src/tests/actor-spam-test.ts
- packages/functional-tests/src/tests/altspacevr-video-test.ts
- packages/functional-tests/src/tests/asset-preload-test.ts
- packages/functional-tests/src/tests/asset-unload-test.ts
- packages/functional-tests/src/tests/collision-layer-test.ts
- packages/functional-tests/src/tests/grab-test.ts
- packages/functional-tests/src/tests/interpolation-test.ts
- packages/functional-tests/src/tests/light-test.ts
- packages/functional-tests/src/tests/physics-sim-test.ts
- packages/functional-tests/src/tests/primitives-test.ts
- packages/functional-tests/src/tests/prompt-test.ts
- packages/functional-tests/src/tests/sound-test.ts
- packages/functional-tests/src/tests/user-mask-test.ts
- packages/functional-tests/src/tests/video-test.ts
- packages/sdk/src/types/primitiveTypes.ts
- packages/sdk/src/types/runtime/actor.ts
- packages/sdk/src/types/runtime/physics/colliderGeometry.ts
- packages/sdk/src/types/runtime/physics/colliderType.ts
It was bothering me that invalid fields like `uSegments` were showing up in intellisense when creating a box primitive, so I modified the type definition to discriminate by primitive type.
At the same time, I changed `ColliderType` to be an enum, to align with our newly established coding guideline that we don't use string-union types where enums would suffice.
TODO: ColliderType needs docstrings.
TODO: *PrimitiveDefinition needs better docstrings.
> [minor] Make PrimitiveDefinition a discriminated union

- packages/functional-tests/src/test.ts
- packages/functional-tests/src/tests/collision-layer-test.ts
* Fixed bug where moderator-restricted tests couldn't be run in the Testbed
* Fixed bad assumptions in collision-layer-test
> Fix test bugs

- packages/gltf-gen/src/vertexattributes.ts
> Fix copy/paste error in gltf-gen color vertex attributes

- packages/sdk/src/actor/behaviors/buttonBehavior.ts
- packages/sdk/src/actor/behaviors/targetBehavior.ts
- packages/sdk/src/asset/material.ts
- packages/sdk/src/asset/mesh.ts
- packages/sdk/src/asset/prefab.ts
- packages/sdk/src/asset/sound.ts
- packages/sdk/src/asset/texture.ts
- packages/sdk/src/asset/videoStream.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientExecution.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientHandshake.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientStartup.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionExecution.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionHandshake.ts
- packages/sdk/src/internal/adapters/multipeer/protocols/sessionSync.ts
- packages/sdk/src/internal/connection/eventedConnection.ts
- packages/sdk/src/internal/connection/webSocket.ts
- packages/sdk/src/internal/protocols/execution.ts
- packages/sdk/src/internal/protocols/handshake.ts
- packages/sdk/src/internal/protocols/sync.ts
- packages/sdk/src/internal/util/verifyClient.ts
- packages/sdk/src/util/webHost.ts
Fix the circular dependencies after I reorganized file imports in the codebase in #482.
> Fix import exceptions from #482

- packages/sdk/src/internal/adapters/multipeer/rules.ts
Makes the object-spawned handler slightly more resilient to bad assumptions.
> Fix edge case where object-spawned has unknown actors

- packages/sdk/src/internal/adapters/multipeer/protocols/clientSync.ts
- packages/sdk/src/internal/adapters/multipeer/session.ts
For create-animation messages, merge the latest anim state into the create call instead of sending a separate update payload.
> Sync animation updates in create calls

- packages/functional-tests/src/tests/physics-bounce-test.ts
- packages/functional-tests/src/tests/physics-friction-test.ts
Recent changes to the text component make it incompatible with having another mesh on the same Actor. This has been the case in Altspace for some time, but a recent change to the MRETestBed.
I also added colors to the physics shapes.
> Remove text component from physics planes

- packages/sdk/src/internal/adapters/multipeer/rules.ts
See https://github.com/microsoft/mixed-reality-extension-sdk/issues/509#issuecomment-611472327
This is required in order to set media state (volume, stop, etc...).
> Fix sync for videostream when duration is 0 (live video/audio)

- .eslintrc.js
- packages/sdk/src/actor/physics/collider.ts
* Allow TODO comments for the time being.
* Fix formatting in collider.ts.
> Cleanup lint warnings

- packages/sdk/src/internal/adapters/multipeer/clientDesyncPreprocessor.ts
- packages/sdk/src/internal/adapters/multipeer/rules.ts
Bug: If you update the children of a user-exclusive prefab, those children will not be marked exclusive, even though they only exist on one client. This causes actor updates to be sent to all clients, backing up queues and breaking anything relying on `ActorManager.uponStable`.
Fix: Associate those children with the exclusive parent in the sync layer.
> Fix new prefab children of exclusive roots

- DEPLOYING.md
Added instructions for modifying the dockerfile, using wss://your-site-name.openode.io/, and having the openode.io site open when deploying.
> Updated Openode Deployment

- packages/functional-tests/src/tests/user-mask-test.ts
- packages/sdk/src/user/groupMask.ts
- packages/sdk/src/user/index.ts
- packages/sdk/src/user/invertedGroupMask.ts
Add the concept of a GroupMask containing everything *but* the specified groups.
> Add inverted group mask

- packages/sdk/src/internal/adapters/multipeer/rules.ts
* Fix a bad assumption in the `assets-loaded` rule.
* Add a timeout to asset loads, so they can't hang indefinitely.
> Better handle asset load failures

- packages/functional-tests/src/tests/actor-attachment-test.ts
- packages/functional-tests/src/tests/index.ts
Adding a functional test that tests the actor attachment API
This spawns a large oblong box that attaches to the avatar of the user initiating the test, and two control cubes. The Red/Blue cube cycles between destroying and recreating the attachment when the cube is red, and re-attaching the same actor when the cube is blue. The grey box with the attachment name floating over it cycles between attachment points.
Currently, this passes when the attachment is destroyed every time, but reattaching the same actor leads to improper transforms.
I wasn't able to find anything obvious off the bat in the SDK code that could lead to this, if it makes sense I can open an issue.
> Adding Actor Attachment Test

- design/user.filtering.md
- packages/altspacevr-extras/src/index.ts
- packages/altspacevr-extras/src/moderatorFilter.ts
- packages/altspacevr-extras/src/singleEventFilter.ts
- packages/altspacevr-extras/src/userFilter.ts
- packages/functional-tests/src/tests/altspacevr-user-filter-test.ts
- packages/functional-tests/src/tests/index.ts
- packages/sdk/src/core/context.ts
- packages/sdk/src/util/index.ts
- packages/sdk/src/util/userFilter.ts
* Add a general-purpose API for writing classes that filter user joins, leaves, and interactions.
* Implement a filter that accepts AltspaceVR moderators.
* Implement a filter that accepts users that are in the same event or space as the first user to join.
> Add utilities to filter Altspace users by role or event/space

- packages/sdk/src/util/manifestSchema.json
Catch manifest misspellings and other errors by disallowing unexpected properties. The error message will look like this:
```
2020-08-10T17:56:36.429Z app Node: v12.17.0
2020-08-10T17:56:36.437Z app @microsoft/mixed-reality-extension-sdk: v0.20.0
2020-08-10T17:56:36.446Z app App manifest "C:\Users\stvergen\Projects\mre-sdk\packages\functional-tests\public\manifest.json" is not valid:
instance additionalProperty "requiredPermissions" exists in instance when not allowed
2020-08-10T17:56:36.460Z app Multi-peer Adapter listening on {"address":"::","family":"IPv6","port":3901}
2020-08-10T17:56:36.461Z app baseUrl: http://127.0.0.1:3901
2020-08-10T17:56:36.461Z app baseDir: C:\Users\stvergen\Projects\mre-sdk\packages\functional-tests\public
2020-08-10T17:56:36.461Z app No MRE manifest provided, …
```
> Disallow additional properties in manifests

- packages/functional-tests/src/tests/button-behavior-test.ts
- packages/functional-tests/src/tests/index.ts
This test has just a square button in the middle of the scene and text above it. The text changes from the default state to indicate if the button detects either a quick click or a hold, then back to the default text after 1000 ms.
> button-behavior test V0

- packages/sdk/src/internal/adapters/multipeer/rules.ts
This fixes a bug that causes actor creation lockups on clients that receive these updates.
> Don't sync transforms of grabbed exclusive actors
